volumes:
  postgres_storage:

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      - postgres_storage:/var/lib/postgresql/data
  
  n8n:
    image: n8nio/n8n
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
    links:
      - postgres
    ports:
      - ${N8N_PUBLIC_PORT}:5678
  
  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/site-n8n.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - n8n
